### ISSUE TITLE
doubt conditional fetching

### ISSUE THREAD

**Issue by dededavida** [nandorojo/swr-react-native#1]
hello,I'm facing a problem with the conditional fetching, I did it according to the documentation, but it stays with undefined data forever, this affects because I put a loading and the same always meeting this condition, it could give me a light

**Comment by nandorojo** [comment]
Please leave a code sample and a way to reproduce that this isn't working. I'll re-open if you can include a link to a code sandbox, thanks.

Make sure you use `null` for conditional fetching.
