### ISSUE TITLE
Bump SWR dependency

### ISSUE THREAD

**Issue by outaTiME** [nandorojo/swr-react-native#13]
It would be nice to put SWR as peerDependency or update it to its latest version (1.0.1)

**Comment by nandorojo** [comment]
I agree, but there are a number of breaking changes (like not including global mutate anymore) that would break the current version.

**Comment by nandorojo** [comment]
Oh sorry I thought this was swr-firestore lol. Sure we can do that.

**Comment by te-online** [comment]
Looks like `index.ts` is already adjusted to `mutate` replacing `revalidate`? I haven't tested, but is there anything blocking a new release? 😊

**Comment by nandorojo** [comment]
That’s correct. For now you can use yarn resolutions to change the SWR version. I would also accept a PR

**Comment by te-online** [comment]
Great, I did update swr, actually, but it looks to me that a new npm release would be needed? 🙂

**Comment by nandorojo** [comment]
Sorry I missed that @te-online, published in `1.1.1` using latest SWR as a dev dependency (rather than a nested dependency)

**Comment by nandorojo** [comment]
Documented release here: https://github.com/nandorojo/swr-react-native/releases/tag/1.1.2

I also added the ability to use hooks outside of React Navigation screens.

**Comment by te-online** [comment]
@nandorojo I discovered that I was using [this package](https://www.npmjs.com/package/swr-react-native). Maybe it'd make sense to remove it or update the Readme to point to the [new package](https://www.npmjs.com/package/@nandorojo/swr-react-native) 🙂

**Comment by nandorojo** [comment]
ah yeah 😅
