### ISSUE TITLE
Possible change in readme

### ISSUE THREAD

**Issue by anabeatrizzz** [nandorojo/swr-react-native#14]
Currently, README file tells that `revalidate` function is [required](https://github.com/nandorojo/swr-react-native/blob/05ce89d98562145e27118e82f5dc861f5165f7c0/README.md#L115), but SWR doesn't returns this param anymore: https://github.com/vercel/swr/issues/241#issuecomment-941453434

**Comment by nandorojo** [comment]
Feel free to PR and change to `mutate`.
