### ISSUE TITLE
RemoveEventListener has been deprecated 

### ISSUE THREAD

**Issue by marcosdourado** [nandorojo/swr-react-native#16]
Getting the message that the AppState's removeEventListener has been deprecated and that the remove provided by the addEventListener return should be used.

"react": "17.0.2",
 "react-native": "0.66.4",

**Comment by nandorojo** [comment]
are you using @nandorojo/swr-react-native?

**Comment by nandorojo** [comment]
oh i see. i’d accept a PR to help newer versions of RN, as long as it retains old behavior.

**Comment by marcosdourado** [comment]
I'll upload one with the solution.

**Comment by nandorojo** [comment]
Released in 1.2.0.
