### ISSUE TITLE
AsyncStorage as a cache provider

### ISSUE THREAD

**Issue by calderwoodra** [nandorojo/swr-react-native#24]
Hey there :wave: I've recently started migrating my NextJS site to RN/RNW + Next/Solito. 

When I was using just Next, I had some screens that loaded fairly slowly because of some long, blocking requests. I was able to speed up the page speed significantly with SSR. Now I'm trying to figure out how I can speed up these page loads with Expo/RN. 

Some ideas I'm floating are:
- [Setting SSR data as a SWRConfig fallback](https://swr.vercel.app/docs/with-nextjs#pre-rendering-with-default-data) on the Next JS side
- OTA-ing bundled json file(s) to fill the SWRConfig fallback on the Expo RN side
- Replacing the SWR Cache with [AsyncStorage](https://github.com/react-native-async-storage/async-storage) so that all requests (after the first) are lightning-fast and persisted across sessions

I'm wondering if you've tried anything like this and/or what your thoughts might be here? The AsyncStorage idea seems pretty cool to me and could make sense to add as a config option to this library (happy to take a stab at upstreaming it once I've tried it myself).

**Comment by nandorojo** [comment]
i believe showtime uses mmkv to persist their swr cache. check out their open source repo

**Comment by calderwoodra** [comment]
Awesome, thanks for the pointer (!):
https://github.com/showtime-xyz/showtime-frontend/blob/staging/packages/app/providers/swr-provider.tsx
