### ISSUE TITLE
Plans to support swr 2.0?

### ISSUE THREAD

**Issue by forki** [nandorojo/swr-react-native#26]
Hi,

are there any plans to support swr 2.0?

Thanks

**Comment by nandorojo** [comment]
what’s required for this?

**Comment by forki** [comment]
they have many new features and quite some breaking changes (see https://swr.vercel.app/blog/swr-v2#migration-guide)

**Comment by nandorojo** [comment]
which ones apply to this library?

**Comment by isaacbatst** [comment]
@nandorojo  i have bumped swr version [here](https://github.com/nandorojo/swr-react-native/pull/29) and manually testing i could not notice any  changes needed. What's your testing process, I have noticed there's no automated tests, but do you have a checklist in mind?

**Comment by kkarski** [comment]
Thanks for merging 2.0. Any chance this gets pushed up to npm repo?

**Comment by nandorojo** [comment]
Published
