### ISSUE TITLE
npm package is not correct.

### ISSUE THREAD

**Issue by chj-damon** [nandorojo/swr-react-native#3]
after installing the package, I find out that there's no `dist` folder in it. Maybe you forget to run `yarn build` command to generate dist folder before you publish to npm?

And also, the npm package name is not the same as documented in readme.md. I think it would be a better way to keep npm package name and `name` in package.json the same.

I hope the next release would be soon, I really want to use it in my react-native project.

**Comment by nandorojo** [comment]
Hmm you're right, I'll try to get this fixed today

**Comment by nandorojo** [comment]
`yarn add @nandorojo/swr-react-native`
