### ISSUE TITLE
Error with Expo SDK 46

### ISSUE THREAD

**Issue by crismarucci** [nandorojo/swr-react-native#31]
Hi! I got an error using useSWRNative after upgrading EXPO SDK to v 46. 

`com.facebook.react.bridge.ReadableNativeMap cannot be cast to java.lang.string`

Anyone has bumped into this?

**Comment by nandorojo** [comment]
seems unrelated to swr, no?

**Comment by crismarucci** [comment]
Hi @nandorojo tks for your reply! I have found the issue, reading some of the official doc.
I was using it like this

```
const {data, error} = useSWRNative(
    [url_Endpoint + currentUser.docNumber, currentUser.access_token],
    fetcherToken, {revalidateOnFocus: true}
 )
```
And I changed it to this, and it worked just fine:

```
const {data, error} = useSWRNative(
    [url_Endpoint + currentUser.docNumber, currentUser.access_token],
    ([url, token]) => fetcherToken(url, token), {revalidateOnFocus: true}
 )
```

I don´t fully understand why this was working before upgrading and then it wasn´t, but I'm glad if this could help someone with the same issue.
